"""change column name from image_url to image_path

Revision ID: 1854b2af5dca
Revises: 3482735d4f04
Create Date: 2025-06-28 12:47:51.764431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1854b2af5dca'
down_revision: Union[str, None] = '3482735d4f04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('podcast', sa.Column('image_path', sa.String(), nullable=True))
    op.drop_column('podcast', 'image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('podcast', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('podcast', 'image_path')
    # ### end Alembic commands ###
