"""empty message

Revision ID: 216fb375d1a0
Revises: d55a3e6b0f63
Create Date: 2025-06-21 14:45:11.036192

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "216fb375d1a0"
down_revision: Union[str, None] = "d55a3e6b0f63"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE status ADD VALUE 'failed'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
