"""empty message

Revision ID: 252082184566
Revises: 3c372e3b2078
Create Date: 2025-06-26 11:03:02.429582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '252082184566'
down_revision: Union[str, None] = '3c372e3b2078'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('apple_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_user_apple_id'), 'user', ['apple_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_apple_id'), table_name='user')
    op.drop_column('user', 'apple_id')
    # ### end Alembic commands ###
