"""add thumbnail_updated_at column

Revision ID: 29e35e4bb20a
Revises: 7bb3ed7527d7
Create Date: 2025-07-08 22:28:25.353407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29e35e4bb20a'
down_revision: Union[str, None] = '7bb3ed7527d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('podcast', sa.Column('thumbnail_updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('podcast', 'thumbnail_updated_at')
    # ### end Alembic commands ###
