"""add image_url to podcast table

Revision ID: 3482735d4f04
Revises: 9d6fc7682152
Create Date: 2025-06-28 12:35:56.630289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3482735d4f04'
down_revision: Union[str, None] = '9d6fc7682152'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('podcast', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('podcast', 'image_url')
    # ### end Alembic commands ###
