"""add episode cover and cover description

Revision ID: 3a889ed3a382
Revises: 1854b2af5dca
Create Date: 2025-07-03 20:03:01.708027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a889ed3a382'
down_revision: Union[str, None] = '1854b2af5dca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('episode', sa.Column('cover', sa.String(), nullable=True))
    op.add_column('episode', sa.Column('cover_description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('episode', 'cover_description')
    op.drop_column('episode', 'cover')
    # ### end Alembic commands ###
