"""add subscription tier

Revision ID: 3be804d8d7fd
Revises: 1526ae7f28df
Create Date: 2025-07-26 20:26:08.359966

"""

from typing import Sequence, Union

from alembic import op
from sqlalchemy import text

# revision identifiers, used by Alembic.
revision: str = "3be804d8d7fd"
down_revision: Union[str, None] = "1526ae7f28df"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        text("""
            INSERT INTO subscription_tier (id, tier, max_podcasts, max_daily_episodes, max_daily_extended_episodes)
            VALUES
            (1, 'free', 1, 1, 1),
            (2, 'premium', 4, 12, 4)
            """)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
