"""add foreign key in user table to link with subscription

Revision ID: 3ef9149a3e2a
Revises: 6d40dd3650e1
Create Date: 2025-07-16 23:26:16.259724

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3ef9149a3e2a"
down_revision: Union[str, None] = "6d40dd3650e1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("subscription_tier_id", sa.Integer(), server_default="1", nullable=False)
    )
    op.create_foreign_key(
        "fk_user_subscription_tier", "user", "subscription_tier", ["subscription_tier_id"], ["id"]
    )
    op.create_index("ix_user_subscription_tier_id", "user", ["subscription_tier_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_user_subscription_tier_id", "user")
    op.drop_constraint("fk_user_subscription_tier", "user", type_="foreignkey")
    op.drop_column("user", "subscription_tier_id")  #
    # ### end Alembic commands ###
