"""remove firstname and lastname, and replace with only name for Users table

Revision ID: 447a7b0edcf7
Revises: b3a6ea4c14e2
Create Date: 2025-06-07 19:06:55.288218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '447a7b0edcf7'
down_revision: Union[str, None] = 'b3a6ea4c14e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.String(), nullable=False))
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('user', 'name')
    # ### end Alembic commands ###
