"""add device_id column to user table to allow for guest sign in

Revision ID: 5c5716125f72
Revises: 3ef9149a3e2a
Create Date: 2025-07-22 18:02:30.055253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c5716125f72'
down_revision: Union[str, None] = '3ef9149a3e2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('device_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_user_device_id'), 'user', ['device_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_device_id'), table_name='user')
    op.drop_column('user', 'device_id')
    # ### end Alembic commands ###
