"""remove audio_url and duration from main podcast table

Revision ID: 632712edc658
Revises: e361730f5d3c
Create Date: 2025-06-04 16:16:56.844137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '632712edc658'
down_revision: Union[str, None] = 'e361730f5d3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('podcast', 'audio_url')
    op.drop_column('podcast', 'duration')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('podcast', sa.Column('duration', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('podcast', sa.Column('audio_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
