"""populate subscription table tiers

Revision ID: 64be83e3d711
Revises: 6bebc93c509e
Create Date: 2025-07-23 23:28:28.170669

"""

from typing import Sequence, Union

from alembic import op
from sqlalchemy.sql import text

# revision identifiers, used by Alembic.
revision: str = "64be83e3d711"
down_revision: Union[str, None] = "6bebc93c509e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        text("""
        INSERT INTO subscription_tier (id, tier, max_podcasts, max_daily_episodes, max_daily_extended_episodes)
        VALUES
        (1, 'free', 1, 1, 1),
        (2, 'premium', 4, 12, 4)
        """)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
