"""remove name1 and name2 from db schema

Revision ID: 6b2965dcd1cb
Revises: 62627e9e6b0f
Create Date: 2025-07-06 17:41:21.175700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b2965dcd1cb'
down_revision: Union[str, None] = '62627e9e6b0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('episode', 'name2')
    op.drop_column('episode', 'name1')
    op.drop_column('podcast', 'name2')
    op.drop_column('podcast', 'name1')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('podcast', sa.Column('name1', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('podcast', sa.Column('name2', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('episode', sa.Column('name1', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('episode', sa.Column('name2', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
