"""table init

Revision ID: 6bebc93c509e
Revises:
Create Date: 2025-07-23 23:25:57.781021

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6bebc93c509e"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "subscription_tier",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tier", sa.String(), nullable=False),
        sa.Column("max_podcasts", sa.Integer(), nullable=False),
        sa.Column("max_daily_episodes", sa.Integer(), nullable=False),
        sa.Column("max_daily_extended_episodes", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tier"),
    )
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("apple_id", sa.String(), nullable=True),
        sa.Column("device_id", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("subscription_tier_id", sa.Integer(), server_default="1", nullable=False),
        sa.ForeignKeyConstraint(
            ["subscription_tier_id"],
            ["subscription_tier.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_apple_id"), "user", ["apple_id"], unique=True)
    op.create_index(op.f("ix_user_device_id"), "user", ["device_id"], unique=True)
    op.create_index(
        op.f("ix_user_subscription_tier_id"), "user", ["subscription_tier_id"], unique=False
    )
    op.create_table(
        "podcast",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column(
            "format",
            sa.Enum("interview", "conversation", "story", "analysis", name="format"),
            nullable=False,
        ),
        sa.Column("voice1", sa.Enum("male", "female", name="voice"), nullable=False),
        sa.Column("voice2", sa.Enum("male", "female", name="voice"), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("thumbnail_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_podcast_user_id"), "podcast", ["user_id"], unique=False)
    op.create_table(
        "episode",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("topic", sa.String(), nullable=False),
        sa.Column("length", sa.Enum("short", "long", name="length"), nullable=False),
        sa.Column(
            "format",
            sa.Enum("interview", "coffee_chat", "story", "analysis", name="format"),
            nullable=False,
        ),
        sa.Column("voice1", sa.Enum("male", "female", name="voice"), nullable=False),
        sa.Column("voice2", sa.Enum("male", "female", name="voice"), nullable=True),
        sa.Column("instruction", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("pending", "active", "completed", "cancelled", "failed", name="status"),
            nullable=False,
        ),
        sa.Column("step", sa.Enum("research", "compose", "voice", name="step"), nullable=True),
        sa.Column("hatchet_run_id", sa.String(), nullable=True),
        sa.Column("duration", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("podcast_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["podcast_id"], ["podcast.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_episode_podcast_id"), "episode", ["podcast_id"], unique=False)
    op.create_index(op.f("ix_episode_user_id"), "episode", ["user_id"], unique=False)
    op.create_table(
        "episode_content",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("transcript", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("episode_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["episode_id"], ["episode.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_episode_content_episode_id"), "episode_content", ["episode_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_episode_content_episode_id"), table_name="episode_content")
    op.drop_table("episode_content")
    op.drop_index(op.f("ix_episode_user_id"), table_name="episode")
    op.drop_index(op.f("ix_episode_podcast_id"), table_name="episode")
    op.drop_table("episode")
    op.drop_index(op.f("ix_podcast_user_id"), table_name="podcast")
    op.drop_table("podcast")
    op.drop_index(op.f("ix_user_subscription_tier_id"), table_name="user")
    op.drop_index(op.f("ix_user_device_id"), table_name="user")
    op.drop_index(op.f("ix_user_apple_id"), table_name="user")
    op.drop_table("user")
    op.drop_table("subscription_tier")
    # ### end Alembic commands ###
