"""add a new subscription_tier table

Revision ID: 6d40dd3650e1
Revises: d28a335664e9
Create Date: 2025-07-14 14:40:27.595595

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6d40dd3650e1"
down_revision: Union[str, None] = "d28a335664e9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "subscription_tier",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tier", sa.String(), nullable=False),
        sa.Column("max_podcasts", sa.Integer(), nullable=False),
        sa.Column("max_daily_episodes", sa.Integer(), nullable=False),
        sa.Column("max_daily_extended_episodes", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tier"),
    )

    op.execute(
        sa.text("""
           INSERT INTO subscription_tier (id, tier, max_podcasts, max_daily_episodes, max_daily_extended_episodes)
           VALUES
           (1, 'free', 3, 3, 1),
           (2, 'premium', 12, 12, 3)
           """)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("subscription_tier")
    # ### end Alembic commands ###
