"""remove apple_id from user table for now

Revision ID: 6fa6352a6d99
Revises: 3be804d8d7fd
Create Date: 2025-07-26 22:01:34.853000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fa6352a6d99'
down_revision: Union[str, None] = '3be804d8d7fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_apple_id'), table_name='user')
    op.drop_column('user', 'apple_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('apple_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_user_apple_id'), 'user', ['apple_id'], unique=True)
    # ### end Alembic commands ###
