"""drop image_path column from podcast table

Revision ID: 7bb3ed7527d7
Revises: 6b2965dcd1cb
Create Date: 2025-07-08 14:26:27.043662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bb3ed7527d7'
down_revision: Union[str, None] = '6b2965dcd1cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('podcast', 'image_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('podcast', sa.Column('image_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
