"""add cover step to the Step enum

Revision ID: 8097c143ff18
Revises: 3a889ed3a382
Create Date: 2025-07-03 21:46:56.525388

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8097c143ff18"
down_revision: Union[str, None] = "3a889ed3a382"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE step ADD VALUE 'cover' BEFORE 'voice'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
