"""change url to file_name in podcast_audio

Revision ID: 865173afbdbe
Revises: 756ffc63f344
Create Date: 2025-06-16 18:51:46.693443

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
# revision identifiers, used by Alembic.
revision: str = '865173afbdbe'
down_revision: Union[str, None] = '756ffc63f344'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('podcast_audio', 'url', new_column_name='file_name')
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('podcast_audio', 'file_name', new_column_name='url')
    # ### end Alembic commands ###
