"""update episode model schema

Revision ID: 9d6fc7682152
Revises: c8c3f170f5aa
Create Date: 2025-06-27 20:43:30.815028

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "9d6fc7682152"
down_revision: Union[str, None] = "c8c3f170f5aa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "episode",
        sa.Column("voice1", postgresql.ENUM(name="voice", create_type=False), nullable=False),
    )
    op.add_column("episode", sa.Column("name1", sa.String(), nullable=True))
    op.add_column(
        "episode",
        sa.Column("voice2", postgresql.ENUM(name="voice", create_type=False), nullable=True),
    )
    op.add_column("episode", sa.Column("name2", sa.String(), nullable=True))
    op.drop_column("episode", "voice")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "episode",
        sa.Column(
            "voice",
            postgresql.ENUM("male", "female", name="voice"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("episode", "name2")
    op.drop_column("episode", "voice2")
    op.drop_column("episode", "name1")
    op.drop_column("episode", "voice1")
    # ### end Alembic commands ###
