"""remove level from episode and pocast table

Revision ID: b3b225421fc7
Revises: 0e7e1a5e9a9a
Create Date: 2025-07-25 10:33:22.033972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b3b225421fc7'
down_revision: Union[str, None] = '0e7e1a5e9a9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('episode', 'level')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('episode', sa.Column('level', postgresql.ENUM('beginner', 'intermediate', 'advanced', name='level'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
