"""add new podcast table

Revision ID: c8c3f170f5aa
Revises: ed3af658ee8a
Create Date: 2025-06-27 19:56:37.967404

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c8c3f170f5aa"
down_revision: Union[str, None] = "ed3af658ee8a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "podcast",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("format", postgresql.ENUM(name="format", create_type=False), nullable=False),
        sa.Column("voice1", postgresql.ENUM(name="voice", create_type=False), nullable=False),
        sa.Column("name1", sa.String(), nullable=True),
        sa.Column("voice2", postgresql.ENUM(name="voice", create_type=False), nullable=True),
        sa.Column("name2", sa.String(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_podcast_user_id"), "podcast", ["user_id"], unique=False)
    op.add_column("episode", sa.Column("podcast_id", sa.Integer(), nullable=False))
    op.create_index(op.f("ix_episode_podcast_id"), "episode", ["podcast_id"], unique=False)
    op.create_foreign_key(None, "episode", "podcast", ["podcast_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "episode", type_="foreignkey")
    op.drop_index(op.f("ix_episode_podcast_id"), table_name="episode")
    op.drop_column("episode", "podcast_id")
    op.drop_index(op.f("ix_podcast_user_id"), table_name="podcast")
    op.drop_table("podcast")
    # ### end Alembic commands ###
