"""add daily credit to subscription tier table and drop the hard limit on regular and long episode

Revision ID: d21097e290e9
Revises: 6fa6352a6d99
Create Date: 2025-08-02 18:01:31.143523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd21097e290e9'
down_revision: Union[str, None] = '6fa6352a6d99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription_tier', sa.Column('daily_credit', sa.Integer(), server_default='0', nullable=False))
    op.drop_column('subscription_tier', 'max_daily_episodes')
    op.drop_column('subscription_tier', 'max_daily_extended_episodes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription_tier', sa.Column('max_daily_extended_episodes', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('subscription_tier', sa.Column('max_daily_episodes', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('subscription_tier', 'daily_credit')
    # ### end Alembic commands ###
