"""add a new hatchet_run_id column to the podcast table to be able to cancel run

Revision ID: d55a3e6b0f63
Revises: 865173afbdbe
Create Date: 2025-06-21 13:46:30.322548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd55a3e6b0f63'
down_revision: Union[str, None] = '865173afbdbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('podcast', sa.Column('hatchet_run_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('podcast', 'hatchet_run_id')
    # ### end Alembic commands ###
