"""change credit -> credits

Revision ID: f04e08e6d63f
Revises: d21097e290e9
Create Date: 2025-08-02 18:13:40.484646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f04e08e6d63f'
down_revision: Union[str, None] = 'd21097e290e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription_tier', sa.Column('max_daily_credits', sa.Integer(), server_default='0', nullable=False))
    op.drop_column('subscription_tier', 'daily_credit')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription_tier', sa.Column('daily_credit', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.drop_column('subscription_tier', 'max_daily_credits')
    # ### end Alembic commands ###
