"""add a new title column in table content

Revision ID: f7a562aff4d3
Revises: cb8982618086
Create Date: 2025-06-04 16:09:15.439271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f7a562aff4d3'
down_revision: Union[str, None] = 'cb8982618086'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('podcastcontent', sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), server_default='Untitled', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('podcastcontent', 'title')
    # ### end Alembic commands ###
